mutation upsertTags($objects: [tags_insert_input!]!) {
  insert_tags(
    objects: $objects
    on_conflict: {
      constraint: tags_slug_userId_key
      update_columns: [name, slug]
    }
  ) {
    affected_rows
    returning {
      uuid
      name
    }
  }
}
