query getAllItemsByCat {
  cats {
    name
    uuid
    items_cats {
      item {
        uuid
        name
        slug
        desc
        updated_at
        url
        user {
          uuid
        }
        items_tags {
          tag {
            uuid
            name
            slug
          }
        }
      }
    }
  }
}
