query getItemsByTag($uuid: uuid!) {
  tags(where: { uuid: { _eq: $uuid } }) {
    name
    slug
    uuid
    items_tags {
      item {
        desc
        uuid
        name
        slug
        url
        desc
        updated_at
        uuid
        items_tags {
          tag {
            updated_at
            slug
            name
            uuid
          }
        }
      }
    }
  }
}
