query getItemsByCat($uuid: uuid!) {
  cats(where: { uuid: { _eq: $uuid } }) {
    name
    uuid
    items {
      name
      uuid
      userUuid
      url
      desc
      updated_at
      slug
      items_tags {
        tag {
          uuid
          name
          slug
          uuid
        }
      }
    }
  }
}
