mutation AddItem(
  $itemUuid: uuid!
  $userUuid: uuid!
  $userId: String!
  $name: String!
  $slug: String!
  $url: String!
  $desc: String!
  $catUuid: uuid! # $tags: [items_tags_insert_input!]!
) {
  insert_items(
    objects: [
      {
        uuid: $itemUuid
        name: $name
        slug: $slug
        url: $url
        desc: $desc
        userUuid: $userUuid
        userId: $userId
        catUuid: $catUuid
      }
    ]
    on_conflict: {
      constraint: items_pkey
      update_columns: [name, url, slug, desc]
    }
  ) {
    affected_rows
    returning {
      name
      uuid
    }
  }
  insert_items_cats(
    objects: { itemUuid: $itemUuid, catUuid: $catUuid }
    on_conflict: {
      constraint: items_cats_pkey
      update_columns: itemUuid
    }
  ) {
    returning {
      itemUuid
      catUuid
    }
  }
}
